version: "3.9"

services:
  data-mapper:
    build:
      dockerfile: data-mapper/Dockerfile
      context: .
      args:
        USER_ID: ${USER_ID}
    profiles: ["prod"]
    volumes:
      - type: bind
        source: ./
        target: /log
      - type: volume
        source: data-share
        target: /vol/data-vol
    command: ["mapper.py"]

  png-mapper:
    build:
      dockerfile: png-mapper/Dockerfile
      context: .
      args:
        USER_ID: ${USER_ID}
    profiles: ["prod"]
    volumes:
      - type: bind
        source: ./
        target: /base/images
      - type: volume
        source: data-share
        target: /mapper/vol
    entrypoint: /bin/sh
    command: ["-c", "export HTTPEXEC_EXEC_ROOT='/mapper/src/build/' && python3 -m hypercorn --error-logfile - --access-logfile - --bind png-mapper:8000 httpexec.asgi:app"]
    stdin_open: true
    tty: true

  png-mapper-test:
    build:
      dockerfile: png-mapper/Dockerfile
      target: test
      context: .
      args:
        USER_ID: ${USER_ID}
    profiles: ["test"]
    entrypoint: /bin/sh
    command: ["-c", "cd /mapper && ./test.sh"]

  data-mapper-test:
    build:
      dockerfile: data-mapper/Dockerfile
      target: test
      context: .
      args:
        USER_ID: ${USER_ID}
    profiles: ["test"]
    command: ["pytest"]

volumes:
    data-share:

